<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.Model\Atlas.Model.csproj" />
    <ProjectReference Include="..\Atlas.Storage\Atlas.Storage.csproj" />
  </ItemGroup>

</Project>
