<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <RootNamespace>SevenSeals.Tss.Shared</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Shared.Proto\Shared.Proto.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  
</Project>
